language: go
services:
- docker
go:
- '1.11'
install:
- go get -u github.com/mattn/goveralls
script:
- make docker-build
- goveralls -service=travis-ci
deploy:
  provider: script
  script: make docker-push
  on:
    tags: true
env:
  global:
  - secure: Sc1tM7VP18vHE7aFa52ut4FSp+DOGf2jadHN3gR1F6gAbfvaC7kgx192ztZm2Rxb8AsGADSmofifM22ziiajZw1FH1OLpc1Z9kv5DPZo57I7CcyGodLsZOSc2vJRe7HMaeN1KB1fyFi4hdh31XsIHggIQWV2mMKn0Y4ki7LyRAuTPqVt3Dyzrgsqd01zFcv/Wm0HSSgC4KbLKvTPHCNH11mFmKmAcuOr0N/nqzq91yavLjpeSXXQi5tcVlLCV/m9xMc0Pq0zyxJAzuZK/uEq1YhyvSYnwOHLPgVXNcVtQeW2Olkb0que/03HQZF3pLU+064qCGkhZh2loUeBlIiPV4//R8O9h8eyx32qzMJgUV+t9loAQFnNEEAvMIWa8VFxiIttD6RMeHkk8KxoIbKA/2yD3CH3VIL99oPeXs+3HgRtzfbTvwJvOOtcGvEfxDDeMBJB1tfsk92aMMeB79Qt8RftVwwK7v8mG/hyPPsrmfj1BoYOVad/gEs/PUcmzzrQ9Uh/XgO24BBTup7Ur/x+taELYO69fCDtEfMeE7irYz7EOcuCAxv3Qmd77mXcoWrgb2YETTUnk/ZbZriHE0BVoX9eMNmIP/to11eEj/TZ7qcvjU+Pl9djrTvCE7k1zt8Sg5ZupojCURf+n6TpEju/4yGRte3NFzeAzVoD89u0ZEU=
  - secure: nCK/81aG9dv/Q9HAbpif+zFpyoLZHI+mVe4cpFDRj8eTDtDNWo7jLEy3wuynluvvN1UXb6gwWCbCUAr7dQsukXx1eljR2fQmjrCNPtwFv5sEFef3dEycsCcIR/lW06iDazlMTLpfxvA88b+d5VbEgUuMnHIvXPOx9NA4ETktJn5SnGzrWN4+a58d+JZ4UF7DB2VstBMqYWuN5oPkzi7mhxzDU6KLn1yKN3USkTYJBclyq/stF/tQZf7hcCRlRjweYtWobGKrn0ZFwtDabVRzHghyby022o3R8nYXibZu1idk6FX7LD46nF461A1+C5CoJJmJWlNmGKJ1iMH4inwt0864HjXaFsWz1l0sQA2xh/vgmMvHJBZkRaHqFFVcRQNALGelUZfxsS3PEiBDra0YTRtucx3APGNRnJIQ1K+3g5t3xCrwDx+24GSYbMhILaPevjbmk7dw/2bLOIFpFMQMTmgM2AURbzKHMANIrxMj4x/ATBjX0a2u5aDyhOFb47WQijMnbtz7HiTdf/Tx0BAPXEpm6gG+QdPVuWX87Z3MWR8sqv08m8uojOoXg2CE6YOX2MWfUIHJ40Xuf1XLddWQ2hSthxf5JjTps1goC+KqCqRy/NLKDuru4HRWgqkgEzu75n9RydX5+dY26XIThv3wsbs9nlIxe3E5Qy6aJjEh4cI=
